services:
  vllm:
    container_name: vllm
    restart: no
    image: vllm/vllm-openai:v0.10.0
    ipc: host
    volumes:
      - /home/liontechmdev/data/huggingface:/root/.cache/huggingface
    command:
      - --model
      - Qwen/Qwen3-Coder-30B-A3B-Instruct-FP8
      - --served-model-name
      - Qwen3-Coder-30B-A3B
      - --enable-auto-tool-choice
      - --tool-call-parser
      - qwen3_coder
      - --gpu-memory-utilization
      - "0.95"
      - --max-model-len
      - "100000"
    ports:
      - 8073:8000
    environment:
      - NVIDIA_VISIBLE_DEVICES=2
      - HF_TOKEN=hf_xxx
      # - CUDA_LAUNCH_BLOCKING=1
    runtime: nvidia