services:
  vllm:
    container_name: vllm
    restart: no
    image: vllm/vllm-openai:v0.10.0
    ipc: host
    volumes:
      - ./models:/models
    command: 
      - model
      - Qwen/Qwen3-Coder-30B-A3B-Instruct-FP8
      - --served-model-name
      - Qwen3-Coder-30B-A3B
      - enable-auto-tool-choice
      - tool-call-parser
      - qwen3_coder
    ports:
      -8073:8000
    deploy:
      resources:
        devices:
          - driver: nvidia
            count: all
            # device_ids: ["2"]
            capabilities: [gpu]